language_code: wampis
display_name: Wampis
target_language: spanish

sources:
  document:
    enabled: true
    source_name: pdf_wampis_dictionary
    type: pdf_bilingual_dictionary

    pdf:
      raw_path: "data/raw/wampis/document/wampis_dictionary.pdf"
      start_page: 13
      end_page: 268
      column_gap_margin: 8
      italic_font_markers:
        - "Italic"
        - "Oblique"

    export:
      save_csv: true
      save_xlsx: true

  bible:
    enabled: true
    type: bible_web
    base_url_source: "https://ebible.org/hubNT/"
    base_url_target: "https://ebible.org/spabes/"
    books:
      MAT: 28
      MRK: 16
      LUK: 24
      JHN: 21
      ACT: 28
      ROM: 16
      1CO: 16
      2CO: 13
      GAL: 6
      EPH: 6
      PHP: 4
      COL: 4
      1TH: 5
      2TH: 3
      1TI: 6
      2TI: 4
      TIT: 3
      PHM: 1
      HEB: 13
      JAS: 5
      1PE: 5
      2PE: 3
      1JN: 5
      2JN: 1
      3JN: 1
      JUD: 1
      REV: 22
